title: AIDC 2026
description: Inaugural Workshop on Agentic AI in Offensive and Defensive Cyber Operations.
url: ""
baseurl: ""

theme: null
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
